#!/usr/bin/env atf-sh

. $(atf_get_srcdir)/test_env.sh
init_tests \
	pbuild_tar_help \
	pbuild_tar_invalid_opt \
	pbuild_tar_cut \
	pbuild_tar_hash

DATADIR=$(atf_get_srcdir)/testdata

abuild_tar_help_body() {
	atf_check -s exit:0 \
		-o match:"usage:" \
		pbuild-tar --help
}

abuild_tar_invalid_opt_body() {
	atf_check -s not-exit:0 \
		-e match:"usage:" \
		pbuild-tar --invalid
}

abuild_tar_cut_body() {
	atf_require_prog tar

	echo foo > foo
	echo bar > bar
	tar -cf foo.tar foo
	tar -cf bar.tar bar

	cat foo.tar bar.tar > foobar.tar
	atf_check -o not-match:bar \
		tar -tf foobar.tar

	tar -cf - foo | pbuild-tar --cut > cutted.tar
	cat cutted.tar bar.tar > foobar.tar
	atf_check -o match:bar \
		tar -tf foobar.tar
}

abuild_tar_hash_body() {
	atf_require_prog tar strings

	echo foo > foo
	tar --format=posix -cf - foo | pbuild-tar --hash > foo.tar
	atf_check -o match:foo tar -tvf foo.tar
	atf_check -o match:"PS4-TOOLS.checksum" strings foo.tar
}
